# Generated by Django 2.1.3 on 2018-11-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedWindows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_windows', models.IntegerField(default=0)),
                ('hour_programmed', models.TimeField()),
                ('type_of_windows', models.CharField(choices=[('p', 'Programable'), ('f', 'fixed')], default='f', help_text='Type of Automated Window', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Enter a room name', max_length=60)),
                ('automated_windows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domoticHouse.AutomatedWindows')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=4, default='', max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=4, default='', max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='temperature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domoticHouse.TemperatureControl'),
        ),
    ]
