# Generated by Django 2.1.3 on 2018-11-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domoticHouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
