# Generated by Django 2.1.3 on 2018-11-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domoticHouse', '0002_auto_20181121_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='automated_windows',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domoticHouse.AutomatedWindows'),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domoticHouse.TemperatureControl'),
        ),
    ]
